### ISSUE TITLE
[Operations] Introduce executable-operation core foundation

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gtlab-core#1528]
Parent epic: #1526
Normative contract: ADR 0001 (`docs/dev/architecture/decisions/0001-executable-operations-one-shot-worker.rst`), introduced by #1527 / PR #1533

## Goal

Add the minimal Core API for a transport-neutral `GtExecutableOperation`. It must be possible to register, serialize, reconstruct, and execute an operation in-process using existing GTlab mechanisms.

This issue defines the operation contract and its invocation-local execution context. It does not implement an asynchronous runtime, worker transport, event framing, batch command, or task adapter.

## Operation contract

`GtExecutableOperation` derives from `GtObject` and follows ADR 0001: prepare → compute → commit.

- `requiresProject()` states whether execution also needs a project in addition to detached data.
- `createData()` runs on the originating side. It is lightweight, may read the authoritative project, and returns independently owned detached data or `nullptr`.
- `execute()` is the synchronous, potentially expensive compute step. It may modify detached data and an execution-local project, but never the authoritative originating project. It returns independently owned detached, serializable result data or `nullptr`.
- `applyResult()` runs on the originating side. It is lightweight and is the only step that applies a result to the authoritative project. It receives a nullable, read-only, non-owning result pointer and must report structured success or failure.

Do not add an operation-data hierarchy, result-applicator registry, or another execution model.

## Execution context

`GtOperationExecutionContext` is valid for exactly one `execute()` call. It provides:

- mutable, non-owning access to optional detached data; the operation must not retain the pointer;
- an immutable, opaque, globally unique execution ID with stable text form;
- direct access to the invocation-local `GtExecutionEventStream`;
- cooperative cancellation state that `execute()` can read while another thread requests cancellation.

It does not own, load, or synchronize project state. Project-bound execution obtains its project separately through `GtExecutionContextScope`.

Do not add a `GtExecutionEventSink` interface. The concrete stream is both the operation-facing publisher and the local observable source; local consumers use Qt signals and slots. Event envelopes, ordering, transport, and file/process adapters belong to #1529.

## Module registration and serialization

Add the optional Core/headless `GtOperationInterface` using the existing module mechanism. Modules declare operation `QMetaObject`s; the normal module loader validates that each one is a `GtExecutableOperation` and registers it through `GtObjectFactory`. Module authors need no second registration step.

Operations, detached data, and detached results use the existing Memento/XML and `GtObjectFactory` paths. Do not add an operation-specific factory, registry, type ID, metadata wrapper, serializer, or reconstruction path.

## Tests

Cover a normal Memento/XML roundtrip:

```text
operation → serialize → destroy → reconstruct through GtObjectFactory
          → validate as GtExecutableOperation → execute
```

Also prove that a reconstructed registered `GtObject` which is not an operation is rejected before execution. Keep the test operation reusable for later runtime, cancellation, and event-stream work.

## Out of scope

- asynchronous runtime and execution handles (#1515);
- ordered event stream and stdio/file framing (#1529);
- batch-worker command (#1530) and `ProcessTaskOperation` (#1531);
- executor selection, GUI integration, public operation discovery, and new type-system or serialization infrastructure.

## Acceptance criteria

- [ ] `GtExecutableOperation` implements the ADR prepare → compute → commit contract, including structured `applyResult()` failure.
- [ ] `GtOperationExecutionContext` provides detached data, execution ID, concrete event stream, and observable cancellation state while remaining separate from project context.
- [ ] A module declares operations through `GtOperationInterface`, and the existing module loader and `GtObjectFactory` register them.
- [ ] Existing Memento/XML and factory infrastructure reconstruct operations; non-operations are rejected before execution.
- [ ] No second factory, registry, serializer, type layer, or event-sink hierarchy is introduced.
- [ ] Tests provide a reusable operation and execution context for the later runtime and event-stream issues.
